// Especialidades médicas para seleção no formulário de triagem
export const medicalSpecialties = [
  { value: "cardiologia", label: "Cardiologia" },
  { value: "dermatologia", label: "Dermatologia" },
  { value: "endocrinologia", label: "Endocrinologia" },
  { value: "gastroenterologia", label: "Gastroenterologia" },
  { value: "ginecologia", label: "Ginecologia e Obstetrícia" },
  { value: "neurologia", label: "Neurologia" },
  { value: "oftalmologia", label: "Oftalmologia" },
  { value: "ortopedia", label: "Ortopedia e Traumatologia" },
  { value: "otorrinolaringologia", label: "Otorrinolaringologia" },
  { value: "pediatria", label: "Pediatria" },
  { value: "pneumologia", label: "Pneumologia" },
  { value: "psiquiatria", label: "Psiquiatria" },
  { value: "radiologia", label: "Radiologia" },
  { value: "urologia", label: "Urologia" },
  { value: "anestesiologia", label: "Anestesiologia" },
  { value: "cirurgia-geral", label: "Cirurgia Geral" },
  { value: "cirurgia-plastica", label: "Cirurgia Plástica" },
  { value: "cirurgia-vascular", label: "Cirurgia Vascular" },
  { value: "clinica-geral", label: "Clínica Geral" },
  { value: "emergencia", label: "Medicina de Emergência" },
  { value: "geriatria", label: "Geriatria" },
  { value: "hematologia", label: "Hematologia" },
  { value: "infectologia", label: "Infectologia" },
  { value: "nefrologia", label: "Nefrologia" },
  { value: "oncologia", label: "Oncologia" },
  { value: "patologia", label: "Patologia" },
  { value: "proctologia", label: "Proctologia" },
  { value: "reumatologia", label: "Reumatologia" },
  { value: "medicina-trabalho", label: "Medicina do Trabalho" },
  { value: "medicina-preventiva", label: "Medicina Preventiva" },
  { value: "medicina-nuclear", label: "Medicina Nuclear" },
  { value: "medicina-fisica", label: "Medicina Física e Reabilitação" },
  { value: "medicina-intensiva", label: "Medicina Intensiva" },
  { value: "medicina-familia", label: "Medicina de Família e Comunidade" },
  { value: "nutricao", label: "Nutrologia" },
  { value: "fisioterapia", label: "Fisioterapia" },
  { value: "psicologia", label: "Psicologia" },
  { value: "fonoaudiologia", label: "Fonoaudiologia" },
  { value: "terapia-ocupacional", label: "Terapia Ocupacional" },
  { value: "outras", label: "Outras Especialidades" },
];
