// Especialidades médicas para seleção no formulário de triagem
export const medicalSpecialties = [
  { value: "cardiologista", label: "Cardiologia" },
  { value: "dermatologista", label: "Dermatologia" },
  { value: "endocrinologista", label: "Endocrinologia" },
  { value: "gastroenterologista", label: "Gastroenterologia" },
  { value: "ginecologista", label: "Ginecologia e Obstetrícia" },
  { value: "neurologista", label: "Neurologia" },
  { value: "oftalmologista", label: "Oftalmologia" },
  { value: "ortopedista", label: "Ortopedia e Traumatologia" },
  { value: "otorrinolaringologista", label: "Otorrinolaringologia" },
  { value: "pediatra", label: "Pediatria" },
  { value: "pneumologista", label: "Pneumologia" },
  { value: "psiquiatra", label: "Psiquiatria" },
  { value: "radiologista", label: "Radiologia" },
  { value: "urologista", label: "Urologia" },
  { value: "anestesiologista", label: "Anestesiologia" },
  { value: "cirurgiao-geral", label: "Cirurgia Geral" },
  { value: "cirurgiao-plastico", label: "Cirurgia Plástica" },
  { value: "cirurgiao-vascular", label: "Cirurgia Vascular" },
  { value: "clinico-geral", label: "Clínica Geral" },
  { value: "emergencista", label: "Medicina de Emergência" },
  { value: "geriatra", label: "Geriatria" },
  { value: "hematologista", label: "Hematologia" },
  { value: "infectologista", label: "Infectologia" },
  { value: "nefrologista", label: "Nefrologia" },
  { value: "oncologista", label: "Oncologia" },
  { value: "patologista", label: "Patologia" },
  { value: "proctologista", label: "Proctologia" },
  { value: "reumatologista", label: "Reumatologia" },
  { value: "medico-trabalho", label: "Medicina do Trabalho" },
  { value: "medico-preventiva", label: "Medicina Preventiva" },
  { value: "medico-nuclear", label: "Medicina Nuclear" },
  { value: "medico-fisico", label: "Medicina Física e Reabilitação" },
  { value: "intensivista", label: "Medicina Intensiva" },
  { value: "medico-familia", label: "Medicina de Família e Comunidade" },
  { value: "nutrologista", label: "Nutrologia" },
  { value: "fisioterapeuta", label: "Fisioterapia" },
  { value: "psicologo", label: "Psicologia" },
  { value: "fonoaudiologo", label: "Fonoaudiologia" },
  { value: "terapeuta-ocupacional", label: "Terapia Ocupacional" },
  { value: "outros", label: "Outras Especialidades" },
];
