export const patientData = [
  {
    name: "Maria Silva Santos",
    age: 45,
    status: "Crítico",
    statusKey: "critical",
    time: "14:30",
    diagnosis: "Infarto agudo do miocárdio",
  },
  {
    name: "João Carlos Oliveira",
    age: 32,
    status: "Alto",
    statusKey: "serious",
    time: "15:15",
    diagnosis: "Fratura exposta",
  },
  {
    name: "Ana Paula Costa",
    age: 28,
    status: "Moderado",
    statusKey: "moderate",
    time: "16:00",
    diagnosis: "Gastroenterite aguda",
  },
  {
    name: "Carlos Roberto Lima",
    age: 67,
    status: "Baixo",
    statusKey: "mild",
    time: "16:45",
    diagnosis: "Consulta de rotina",
  },
  {
    name: "Fernanda Alves",
    age: 41,
    status: "Crítico",
    statusKey: "critical",
    time: "17:20",
    diagnosis: "AVC isquêmico",
  },
  {
    name: "Roberto Mendes",
    age: 55,
    status: "Alto",
    statusKey: "serious",
    time: "18:10",
    diagnosis: "Pneumonia severa",
  },
  {
    name: "Lucia Ferreira",
    age: 39,
    status: "Moderado",
    statusKey: "moderate",
    time: "19:00",
    diagnosis: "Hipertensão descontrolada",
  },
  {
    name: "Eduardo Santos",
    age: 23,
    status: "Baixo",
    statusKey: "mild",
    time: "19:30",
    diagnosis: "Exame preventivo",
  },
];
