export const mockMedicalRecordData = {
  id: "b8fa0bab-7d34-4fc5-9f6e-231ac269efe1",
  full_name: "Pedro Ferreira",
  cpf: "15975348625",
  email: "pedro.ferreira@email.com",
  gender: "masculino",
  birth_date: "1982-11-25",
  phone: "81943218765",
  city: "Recife",
  neighborhood: "Graças",
  street: "Rua Joaquim Nabuco",
  block: "167",
  apartment: "167",
  blood_type: "O+",
  blood_pressure: "90.60",
  heart_rate: "110",
  respiratory_rate: "22",
  oxygen_saturation: "92",
  temperature: 35.8,
  chief_complaint: "Fraqueza extrema e desmaios",
  patient_condition: "critical",
  bleeding: 1,
  difficulty_breathing: 1,
  edema: 0,
  nausea: 1,
  vomiting: 0,
  allergy: "Latex, mariscos",
  surgery_history: "Não informado",
  reason_for_consultation: "dsadas",
  symptoms: "dsadsa",
  consultation_datetime: "2025-07-06 19:05:00",
  prescribed_medication: "dsadsa",
  medical_recommendations: "dsadsad",
  doctor_observations: "dasdasdas",
  performed_procedures: "Não informado",
  diagnosis: "Não informado",
  additional_notes: "Não informado",
  created_at: "2025-07-06T19:05:38.000000Z",
  updated_at: "2025-07-06T19:05:38.000000Z",
};

export const medicalRecordLabels = {
  full_name: "Nome Completo",
  cpf: "CPF",
  email: "E-mail",
  gender: "Sexo",
  birth_date: "Data de Nascimento",
  phone: "Telefone",
  city: "Cidade",
  neighborhood: "Bairro",
  street: "Rua",
  block: "Número",
  apartment: "Apartamento",
  blood_type: "Tipo Sanguíneo",
  blood_pressure: "Pressão Arterial",
  heart_rate: "Frequência Cardíaca",
  respiratory_rate: "Frequência Respiratória",
  oxygen_saturation: "Saturação de Oxigênio",
  temperature: "Temperatura",
  chief_complaint: "Queixa Principal",
  patient_condition: "Estado do Paciente",
  bleeding: "Sangramento",
  difficulty_breathing: "Dificuldade para Respirar",
  edema: "Edema",
  nausea: "Náusea",
  vomiting: "Vômito",
  allergy: "Alergias",
  surgery_history: "Histórico de Cirurgias",
  reason_for_consultation: "Motivo da Consulta",
  symptoms: "Sintomas",
  consultation_datetime: "Data e Hora da Consulta",
  prescribed_medication: "Medicação Prescrita",
  medical_recommendations: "Recomendações Médicas",
  doctor_observations: "Observações do Médico",
  performed_procedures: "Procedimentos Realizados",
  diagnosis: "Diagnóstico",
  additional_notes: "Notas Adicionais",
  created_at: "Criado em",
  updated_at: "Atualizado em",
};
